import type { Flashcard } from './types';

export const flashcards: Flashcard[] = [
  {
    id: 'fc-js-01',
    front: 'O que é uma variável em programação?',
    back: 'Um espaço nomeado na memória onde guardamos um valor (número, texto…) para usar ou alterar depois no código.',
    concepts: ['variaveis'],
  },
  {
    id: 'fc-js-02',
    front: 'Qual a diferença entre "let" e "const" em JavaScript?',
    back: '"let" permite reatribuir o valor depois. "const" cria uma constante: o valor não pode ser trocado após a inicialização.',
    concepts: ['variaveis'],
  },
  {
    id: 'fc-js-03',
    front: 'O que acontece ao reatribuir uma variável declarada com "const"?',
    back: 'O JavaScript lança um TypeError ("Assignment to constant variable") e a execução para, porque constantes são imutáveis após a atribuição.',
    concepts: ['variaveis'],
  },
  {
    id: 'fc-js-04',
    front: 'Por que "2" + 3 resulta em "23" e não em 5?',
    back: 'Quando um dos lados do + é uma string, o JavaScript converte o outro em string e junta os dois. Para somar, converta antes com Number().',
    concepts: ['tipos-de-dados', 'operadores'],
  },
  {
    id: 'fc-js-05',
    front: 'Qual a diferença entre = e === ?',
    back: '"=" atribui um valor a uma variável. "===" compara dois valores e devolve true ou false, sem converter tipos. Usar "=" dentro de um if é um erro clássico: em vez de comparar, você atribui.',
    concepts: ['operadores', 'condicoes'],
  },
  {
    id: 'fc-js-06',
    front: 'Num if / else if encadeado, o que acontece depois que uma condição é verdadeira?',
    back: 'O bloco dela executa e todos os seguintes são ignorados — nem chegam a ser testados. Por isso a ordem importa: encadeie da faixa mais restritiva para a mais ampla.',
    concepts: ['condicoes'],
  },
  {
    id: 'fc-js-07',
    front: 'O que causa um laço infinito?',
    back: 'Uma condição de parada que nunca se torna falsa — geralmente porque o contador não avança dentro do loop, ou avança na direção errada.',
    concepts: ['loops', 'depuracao'],
  },
  {
    id: 'fc-js-08',
    front: 'Por que declarar o acumulador ANTES do loop, e não dentro?',
    back: 'Declarado dentro, ele é recriado a cada volta e perde o valor acumulado — o resultado final vira apenas a última parcela. Fora do loop, ele sobrevive entre as iterações.',
    concepts: ['loops', 'variaveis'],
  },
  {
    id: 'fc-js-09',
    front: 'Num array de 3 itens, quais índices são válidos?',
    back: '0, 1 e 2. A contagem começa em zero, então o último índice é sempre length - 1. Acessar a posição 3 devolve undefined em silêncio, sem lançar erro.',
    concepts: ['arrays'],
  },
  {
    id: 'fc-js-10',
    front: 'Qual a diferença entre console.log e return dentro de uma função?',
    back: 'console.log mostra algo na tela; return entrega um valor de volta a quem chamou a função. Uma função que só imprime devolve undefined e não pode ter o resultado reaproveitado numa conta.',
    concepts: ['funcoes'],
  },
  {
    id: 'fc-js-11',
    front: 'Por que 0.1 + 0.2 não é exatamente 0.3?',
    back: 'Números decimais são guardados em binário, e frações como 0,1 não têm representação exata — assim como 1/3 não termina em decimal. Em valores monetários, arredonde na exibição (toFixed), lembrando que toFixed devolve texto, não número.',
    concepts: ['tipos-de-dados', 'operadores'],
  },
  {
    id: 'fc-js-12',
    front: 'Por que "Cannot read properties of undefined" acontece?',
    back: 'Porque você tentou ler algo DENTRO de um valor que é undefined. O nome existe, mas o conteúdo não — então verifique o nível de cima antes de descer mais um.',
    concepts: ['objetos', 'depuracao'],
  },
  {
    id: 'fc-js-13',
    front: 'Qual a diferença entre ReferenceError e TypeError?',
    back: 'ReferenceError: o NOME não existe (erro de digitação ou escopo). TypeError: o nome existe, mas o VALOR não é do tipo que você supôs.',
    concepts: ['depuracao'],
  },
  {
    id: 'fc-js-14',
    front: 'Quando usar map, filter e reduce?',
    back: 'map transforma cada item e devolve um array do mesmo tamanho. filter seleciona e devolve um menor ou igual. reduce condensa tudo num único valor. Nenhum dos três altera o array original.',
    concepts: ['arrays'],
  },
  {
    id: 'fc-js-15',
    front: 'Para pegar os nomes só dos itens aprovados, qual a ordem: map ou filter primeiro?',
    back: 'filter primeiro, map depois. Se você transformar em nomes antes, perde a informação usada para filtrar.',
    concepts: ['arrays'],
  },
  {
    id: 'fc-js-16',
    front: 'Por que texto.trim() sozinho não limpa a variável?',
    back: 'Strings são imutáveis: o método devolve um texto NOVO em vez de alterar o existente. É preciso guardar o retorno — texto = texto.trim().',
    concepts: ['strings'],
  },
  {
    id: 'fc-js-17',
    front: 'Quais casos extremos testar antes de considerar uma função pronta?',
    back: 'Vazio, um único item, o limite exato da regra, negativo e zero, valores repetidos e tipo errado. O caso mais perigoso não é o que dá erro — é o que devolve valor errado em silêncio.',
    concepts: ['casos-extremos'],
  },
  {
    id: 'fc-js-18',
    front: 'A regra diz "acima de 100". Devo usar > ou >= ?',
    back: '> apenas. "Acima de 100" exclui o próprio 100. Confundir os dois é o erro de um a mais, e só um teste no valor exato do limite revela.',
    concepts: ['casos-extremos', 'condicoes'],
  },
  {
    id: 'fc-js-19',
    front: 'Num acumulador de multiplicação, qual o valor inicial?',
    back: '1, não 0. Começar em zero zera todo o resultado na primeira multiplicação. Para soma o inicial é 0; para produto é 1.',
    concepts: ['loops', 'simulacao'],
  },
  {
    id: 'fc-js-20',
    front: 'Qual é o primeiro passo ao receber um problema grande?',
    back: 'Listar os passos menores antes de escrever código, e perguntar: qual é a menor parte disso que eu já saberia fazer agora? Cada passo deve ser testável sozinho.',
    concepts: ['decomposicao'],
  },
  {
    id: 'fc-js-21',
    front: 'Por que prever a saída antes de executar o código?',
    back: 'Quando a previsão bate, sua compreensão está correta. Quando não bate, você encontrou o ponto exato onde seu modelo mental está errado — a informação mais valiosa que existe para aprender.',
    concepts: ['simulacao'],
  },
  {
    id: 'fc-js-22',
    front: 'Por que remover itens com splice dentro de um loop pula elementos?',
    back: 'Porque splice altera o array durante a iteração: os índices seguintes deslizam para trás enquanto o contador avança. Prefira filter, que devolve uma lista nova.',
    concepts: ['arrays', 'depuracao'],
  },
];
